ubuntu2004:
  image: focal-server-cloudimg-amd64.img

large:
  image: focal-server-cloudimg-amd64.img
  numcpus: 4
  memory: 12288
  disks:
  - size: 150

medium:
  image: focal-server-cloudimg-amd64.img
  numcpus: 2
  memory: 4086
  disks:
  - size: 50

small:
  image: focal-server-cloudimg-amd64.img
  numcpus: 1
  memory: 2048

micro:
  image: focal-server-cloudimg-amd64.img
  numcpus: 1
  memory: 1024

tester:
  image: focal-server-cloudimg-amd64.img
  numcpus: 1
  memory: 2048
  cmds:
  - su - ubuntu -c 'git clone https://github.com/yevgenybulochnik/dotfiles.git ~/dotfiles'
  - su - ubuntu -c '~/dotfiles/setup.sh --minimal-setup'
  - su - ubuntu -c 'vim'
